version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: encanto_db
    restart: always
    environment:
      POSTGRES_USER: encanto_user
      POSTGRES_PASSWORD: encanto_password
      POSTGRES_DB: encanto_tickets
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U encanto_user -d encanto_tickets"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: encanto_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://encanto_user:encanto_password@postgres:5432/encanto_tickets
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=encanto_user
      - DB_PASSWORD=encanto_password
      - DB_NAME=encanto_tickets
      - JWT_SECRET=sua_chave_secreta_jwt_aqui
      - GEMINI_API_KEY=COLOQUE_SUA_CHAVE_AQUI
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: encanto_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
